/**
 * Static picklists for San Miguel's applicant form, sourced verbatim from
 * reference/official-application-form/fields.json (the real, currently-live
 * BPLO intake form's own field config -- extracted 2026-08-13, see that
 * folder's README.md for provenance).
 *
 * Kept as static TS constants rather than a DB table: these are descriptive
 * enumerations (business-type names, barangay names), not the fee/rate/
 * business-type *logic* CLAUDE.md rule #1 is about. If MuniServe ever needs
 * a second LGU with its own picklists, this is the file to turn into a
 * per-LGU lookup -- flagged here rather than solved now.
 */

export const NATURE_OF_BUSINESS_OPTIONS = [
  "Piggery/Hog Raising",
  "Poultry Farm",
  "Chicken Farm",
  "Fish Pond/Aquaculture",
  "Vegetable Farming",
  "Rice/Corn Farming",
  "Flower Farm",
  "Plant Nursery/Garden Center",
  "Rice Mill",
  "Ice Plant",
  "Purified/Mineral Water Plant",
  "Bottled Water Production",
  "T-shirt Printing/Sublimation",
  "Welding Shop",
  "Steel Fabrication",
  "Bakery (Manufacturing)",
  "Garment Manufacturing",
  "Furniture Manufacturing",
  "Hollow Blocks/Concrete Products",
  "Food Processing",
  "Soap/Detergent Manufacturing",
  "Handicraft Manufacturing",
  "Print Shop",
  "Junk Shop/Scrap Dealer",
  "Recycling Shop",
  "General Contractor",
  "Civil/Road Works Contractor",
  "Electrical Services",
  "Plumbing Services",
  "Air Conditioning Installation",
  "Painting Services",
  "Tile/Masonry Works",
  "Pest Control Services",
  "Sari-sari Store",
  "Mini-mart",
  "Grocery Store",
  "Convenience Store",
  "Supermarket",
  "Department Store",
  "General Merchandise",
  "Cooperative Store",
  "Meat Shop",
  "Fish/Seafood Stall",
  "Vegetable/Fruit Stall",
  "Rice Retailer",
  "Liquor Store",
  "Water Refilling Station",
  "Feed/Agri Supply Store",
  "Cellphone Store",
  "Computer/Gadget Store",
  "Electrical Supplies Store",
  "Hardware Store",
  "Construction Materials Store",
  "Plumbing Supply Store",
  "Appliance Store",
  "Furniture Store",
  "Sporting Goods Store",
  "Toy Store",
  "Musical Instruments Store",
  "Boutique/Clothing Store",
  "Shoe Store/Footwear",
  "Fabric/Textile Store",
  "Uniform Shop",
  "Baby/Kids Store",
  "Pharmacy/Drugstore",
  "Jewelry Store",
  "Flower Shop",
  "Optical Shop",
  "Bookstore",
  "School Supplies Store",
  "Office Supplies Store",
  "Ukay-ukay/Thrift Shop",
  "Second-hand Goods Store",
  "Pet Shop",
  "Online Selling/E-commerce",
  "Handicraft/Gift Shop",
  "Gasoline/Fuel Station",
  "LPG/Gas Dealer",
  "Car Dealership",
  "Motorcycle Dealership",
  "Auto Parts Store",
  "Motorcycle Parts Store",
  "Tire Shop",
  "Auto Repair",
  "Motorcycle Repair",
  "Vulcanizing Shop",
  "Car Wash",
  "Aircon Repair/Auto",
  "Bakery (Retail Only)",
  "Trucking Service",
  "Cargo/Freight Service",
  "Courier/Delivery Service",
  "Taxi Operation",
  "Tricycle/Pedicab Operation",
  "Jeepney/AUV Operation",
  "Habal-habal/Moto Transport",
  "Car Rental",
  "Warehouse/Storage Facility",
  "Hotel",
  "Resort/Beach Resort",
  "Inn/Lodge",
  "Boarding House",
  "Pension House",
  "Dormitory/Bedspace",
  "Transient House",
  "Restaurant",
  "Fast Food",
  "Carinderia/Turo-turo",
  "Canteen",
  "Catering Services",
  "Pizzeria",
  "Food Car",
  "Ice Cream Shop",
  "Lechon/BBQ Stand",
  "Bakeshop (Bake+Sell)",
  "Cafe/Coffee Shop",
  "Milk Tea Shop",
  "Bar/Pub",
  "Restobar",
  "Internet/Broadband Provider",
  "Cable TV Provider",
  "IT/Software Services",
  "Pawnshop",
  "Money Changer/Remittance",
  "Lending Investor",
  "Credit Cooperative",
  "Memorial/Pre-need Plans",
  "Insurance Agency",
  "Apartment/Room Rental",
  "Property Developer/Subdivision",
  "Real Estate Brokerage",
  "Photo Studio",
  "Photography/Videography",
  "Photobooth",
  "Graphic Design Studio",
  "Advertising Agency",
  "Law Firm",
  "Notary Public",
  "Accounting Services",
  "Architecture/Engineering",
  "Consulting Services",
  "Veterinary Clinic",
  "Security Agency",
  "Manpower/Staffing Agency",
  "Recruitment Agency",
  "Janitorial/Cleaning Services",
  "Events Place/Function Hall",
  "Event Planner/Coordinator",
  "BPO/Call Center",
  "Travel Agency",
  "Photocopy/Printing Services",
  "Parking Lot Operation",
  "Tutorial/Review Center",
  "Driving School",
  "Daycare/Preschool",
  "Computer Training Center",
  "Language School",
  "Music School",
  "Dance School/Studio",
  "Sports Academy",
  "Elementary/Grade School",
  "High School/Secondary School",
  "Medical Clinic",
  "Dental Clinic",
  "Diagnostic Laboratory",
  "Physical Therapy/Rehab Center",
  "Dialysis Center",
  "Birth Center/Lying-in Clinic",
  "Home Care Services",
  "Fitness Center/Gym",
  "Internet Cafe / Computer Gaming",
  "Billiard Hall",
  "KTV/Videoke Bar",
  "Cinema/Movie Theater",
  "Amusement Center/Arcade",
  "Sports Complex/Court Rental",
  "Swimming Pool",
  "Bowling Alley",
  "Cockpit/Sabungan",
  "Lottery/Betting Station",
  "Barber Shop",
  "Beauty Parlor/Salon",
  "Nail Salon",
  "Spa/Wellness Center",
  "Massage Parlor",
  "Laundry Shop",
  "Dry Cleaning",
  "Funeral Parlor",
  "Tailoring/Dressmaking",
  "Embroidery/Alteration Shop",
  "Pet Grooming",
  "Tattoo Parlor",
  "Shoe Repair",
  "Watch Repair",
  "Cellphone Repair",
  "Computer Repair",
  "Appliance Repair",
  "Aircon Repair/Services",
  "Tarpaulin Printing",
  "E-loading/Prepaid Loading",
  "Other - BPLO to Determine",
  "Rural Bank",
  "Commercial Bank",
  "Savings Bank",
  "Bank Branch",
  "Finance Company",
  "Finance & Investment Company",
  "Lodging House",
  "Wholesale Liquor Dealer",
  "Lumberyard",
  "Cold Storage",
  "Used Car Lot",
  "Car Exchange",
  "Private Cemetery",
  "Memorial Park",
  "Vocational School",
  "Technical School",
  "Night Club",
  "Cabaret",
  "Dance Hall",
] as const;

export const BARANGAY_OPTIONS = [
  "Bagong Pag-asa",
  "Bagong Silang",
  "Balaong",
  "Balite",
  "Bantog",
  "Bardias",
  "Baritan",
  "Batasan Bata",
  "Batasan Matanda",
  "Biak na Bato",
  "Biclat",
  "Buga",
  "Buliran",
  "Bulualto",
  "Calumpang",
  "Cambio",
  "Camias",
  "Ilog Bulo",
  "King Kabayo",
  "Labne",
  "Lambakin",
  "Magmarale",
  "Malibay",
  "Maligaya",
  "Mandile",
  "Masalipit",
  "Pacalag",
  "Paliwasan",
  "Partida",
  "Pinambaran",
  "Poblacion",
  "Pulong Bayabas",
  "Pulong Duhat",
  "Sacdalan",
  "Salacot",
  "Salangan",
  "San Agustin",
  "San Jose",
  "San Juan",
  "San Vicente",
  "Sapang",
  "Sibul",
  "Sta. Ines",
  "Sta. Lucia",
  "Sta. Rita Bata",
  "Sta. Rita Matanda",
  "Tartaro",
  "Tibagan",
  "Tigpalas",
] as const;

export const BUSINESS_TAX_PAYMENT_OPTIONS = ["Annual", "Bi-Annually", "Quarterly"] as const;

export const ORGANIZATION_TYPE_OPTIONS = ["Sole Proprietorship", "Partnership", "Corporation", "Cooperative", "Other"] as const;

export const REGISTRATION_AUTHORITY_OPTIONS = ["DTI", "SEC", "CDA", "Other"] as const;

export const TAX_TYPE_OPTIONS = ["VAT", "NON-VAT"] as const;

export const GENDER_OPTIONS = ["Male", "Female"] as const;

export const BUSINESS_ACTIVITY_OPTIONS = ["Main Office", "Branch Office Only", "Admin", "Warehouse", "Others"] as const;

export const OPERATION_ADDRESS_OPTIONS = ["The Same as Main Office Address", "Business Operation is in Different Address"] as const;

export const PREMISES_OWNERSHIP_OPTIONS = ["Owned", "Rented", "Other"] as const;

export const YES_NO_OPTIONS = ["Yes", "No"] as const;

export const BARANGAY_CLEARANCE_OPTIONS = ["Yes", "No, generate my Brgy. clearance"] as const;
